### ISSUE TITLE
Documenting the code

### ISSUE THREAD

**Issue by ghost** [jagoly/sqee#1]
Hey, your library is really cool, but you have on big problem with it... you did not took the time to document it really... it should be nice if you would take a bit of time there... I think anyone who would try to work on other project like STS with it would benefit from that... because like when I try to help you in STS 95% of my job is figuring out how the hell to use sqee.

**Comment by ghost** [comment]
Like you could open a git wiki... And I'm sure it would help other human to jump in to help... since there would be more documentation there would be also more google search that leads to the project probably...

**Comment by jagoly** [comment]
Well, SQEE (rpg less so) is actually somewhat documented. You can run the
Doxygen over it to generate documentation.

Documenting STS really isn't feasible yet, since it's in such an early
stage. Everything is still changing. I can try to add more comments as I
work, but full documentation isn't really relevant yet.

**Comment by jagoly** [comment]
Haha whoops, I replied to this via email so I thought it was for STS.

What part of SQEE is lacking in documentation? I don't have any general descriptions of how to use things, but that's more relevant for creating new projects with LibSQEE.

**Comment by ghost** [comment]
Well the whole thing in general... Like the function and stuff... Most of
the time, I find myself just trying to figure out how you wrote the thing
to be able to understand the sts code... Imagine if you were to wrote a gtk
app with gtk+ or gtkmm without any documentation on the library so you
would have to read the whole library code to figure out how to use the
thing actually...

What is doxygen really?

And yea if you could just comment the code a bit more in sts that would
also help a lots
